public class HarvestProject {
 
    public String id { get; set; }
    public String name { get; set; }
    public Boolean active { get; set; }
    public Boolean billable { get; set; }
    public String billBy { get; set; }
    public String clientId { get; set; }
    public String code { get; set; }
    public String notes { get; set; }
    public String budgetBy { get; set; }
    public String budget { get; set; }
    public String fees { get; set; }
    
}