public class HarvestContact {
    
    public string id { get; set; }
    public string clientId { get; set; }
    public string email { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string phone { get; set; }
    public string mobile { get; set; }
    public string fax { get; set; }
    public string title { get; set; }
    public Datetime createdAt { get; set; }
    public Datetime updatedAt { get; set; }
    
}